### ISSUE TITLE
Installaing NPM on Windows

### ISSUE THREAD

**Issue by dinamoedm** [zeldridge/best-buy-sniper#15]

**Comment by dinamoedm** [comment]
I'm getting this guys 👍 

PS C:\Dev\best-buy-sniper-main> npm run start

> best-buy-sniper@0.1.0 prestart C:\Dev\best-buy-sniper-main
> npm run build


> best-buy-sniper@0.1.0 build C:\Dev\best-buy-sniper-main
> tsc

'tsc' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-buy-sniper@0.1.0 build: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-buy-sniper@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PCAdmin\AppData\Roaming\npm-cache\_logs\2021-01-26T03_57_33_695Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-buy-sniper@0.1.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-buy-sniper@0.1.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PCAdmin\AppData\Roaming\npm-cache\_logs\2021-01-26T03_57_33_717Z-debug.log
PS C:\Dev\best-buy-sniper-main>


Any idea what's wrong ? 

Thanks in advance

**Comment by dinamoedm** [comment]
Here is the log 👍 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle best-buy-sniper@0.1.0~prestart: best-buy-sniper@0.1.0
6 verbose lifecycle best-buy-sniper@0.1.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle best-buy-sniper@0.1.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Dev\best-buy-sniper-main\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\amd\ati.ace\core-static;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\WINDOWS\system32\gs\gs8.71\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\AOMEI\AOMEI Backupper 6.3.0;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\Users\PCAdmin\AppData\Local\Programs\Python\Launcher\;C:\Users\PCAdmin\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\PCAdmin\AppData\Local\Programs\Python\Python38\;C:\Users\PCAdmin\AppData\Local\Microsoft\WindowsApps;C:\Users\PCAdmin\AppData\Roaming\npm
8 verbose lifecycle best-buy-sniper@0.1.0~prestart: CWD: C:\Dev\best-buy-sniper-main
9 silly lifecycle best-buy-sniper@0.1.0~prestart: Args: [ '/d /s /c', 'npm run build' ]
10 silly lifecycle best-buy-sniper@0.1.0~prestart: Returned: code: 1  signal: null
11 info lifecycle best-buy-sniper@0.1.0~prestart: Failed to exec prestart script
12 verbose stack Error: best-buy-sniper@0.1.0 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:315:20)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1048:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13 verbose pkgid best-buy-sniper@0.1.0
14 verbose cwd C:\Dev\best-buy-sniper-main
15 verbose Windows_NT 10.0.19041
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
17 verbose node v14.15.4
18 verbose npm  v6.14.10
19 error code ELIFECYCLE
20 error errno 1
21 error best-buy-sniper@0.1.0 prestart: `npm run build`
21 error Exit status 1
22 error Failed at the best-buy-sniper@0.1.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by Emperornero** [comment]
Make sure you "npm install" before attempting to run the program.  Npm install makes sure you have all the dependencies.
